
import React from "react";
import { Inter } from "next/font/google";
import { Toaster} from 'sonner'
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line react/prop-types
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Toaster richColors position="top-center"/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
